version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./mounts/db_data:/home/parth/SNA/'lab 10'/Q_3/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  web:
    image: myapp:nodejs
    depends_on:
     - mongodb
    build: .
    ports:
     - "8080:8080"
    command: >
      bash -c "rm /app/config/database.js && echo 'module.exports = {
              'url' : 'mongodb://root:example@mongo:27017/passport' // looks like mongodb://<user>:<pass>@mongo.onmodulus.net:27017/Mikha4ot
               };' >> /app/config/database.js"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

